-- 1. Inserção de todas as oficinas
INSERT INTO public.oficinas (nome, horario) VALUES
('BACKEND: PYTHON', '10H - 11H'),
('BACKEND: PYTHON', '11H - 12H'),
('DESIGN DIGITAL', '10H - 11H'),
('DESIGN DIGITAL', '11H - 12H'),
('FRONTEND', '10H - 12H'),
('INTELIGÊNCIA ARTIFICIAL', '10H - 12H'),
('DEFESA PESSOAL', '10H - 11H'),
('DEFESA PESSOAL', '11H - 12H'),
('LOGÍSTICA', '10H - 11H'),
('LOGÍSTICA', '11H - 12H'),
('RH', '10H - 11H'),
('RH', '11H - 12H'),
('FINANCEIRO', '10H - 11H'),
('FINANCEIRO', '11H - 12H'),
('MARKETING', '10H - 11H'),
('MARKETING', '11H - 12H');

-- 2. Inserção de todos os alunos (sem duplicidade)
INSERT INTO public.alunos (nome, serie, curso) VALUES
('Amanda Castão Vaz', '1º', 'ADM'),
('Amanda Cristina Constantino', '1º', 'ADM'),
('Bianca Teixeira Preciso', '1º', 'ADM'),
('Felipe Miguel de Oliveira Costa dos Santos', '1º', 'ADM'),
('Fernanda Venancio da Silva', '1º', 'ADM'),
('Gabriel Carnaval', '1º', 'ADM'),
('Jean Luccas', '2º', 'ADM'),
('Lara de Souza Pedrasolli', '1º', 'ADM'),
('Lívia Luz Lemes', '2º', 'ADM'),
('Lorena', '2º', 'ADM'),
('Manuela Moraes do Prado', '1º', 'ADM'),
('Maria Eduarda de Souza', '1º', 'ADM'),
('Maria Laura Candido Novais', '2º', 'ADM'),
('Miguel Ramos', '1º', 'ADM'),
('Natanael Carvalho da Silva', '2º', 'ADM'),
('Raphael De Lima', '1º', 'ADM'),
('Raphaella Orasmo Dalla Pria', '2º', 'ADM'),
('Rayane Vitória Barberdes de Souza', '2º', 'ADM'),
('Vitória Aparecida Adorno da Silva', '1º', 'ADM'),
('Vitória de Oliveira Leite', '1º', 'ADM'),
('Ana Clara Freires de Almeida', '2º', 'ADM'),
('Isabela Zanini', '2º', 'ADM'),
('João de Oliveira Bernardino', '2º', 'ADM'),
('Gabriela Abolis Cardoso', '2º', 'ADM'),
('Rafaela Botin Gonçalves', '1º', 'ADM'),
('Ana Eliza Ribeiro Moura', '1º', 'ADM'),
('Miguel Freire do Amaral', '1º', 'ADM'),
('Gabriel Bordin Souza', '2º', 'ADM'),
('Maria Eduarda Oliveira Lopes', '2º', 'ADM'),
('Ana Laura Pereira Candido', '1º', 'ADM'),
('Giovanna Tadeu Cintra Candido', '1º', 'ADM'),
('Giovanna Pereira de Souza', '1º', 'ADM'),
('Ana Flávia', '1º', 'ADM'),
('Vitor Hugo Basta Fernandes', '2º', 'ADM'),
('João Miguel de Oliveira Santiago', '1º', 'ADM'),
('Maria Cláudia', '2º', 'ADM'),
('Manuela Morais da Silva', '2º', 'ADM'),
('Camilly Cristina Roman da Silva', '2º', 'ADM'),
('Ana Beatriz Santos Dutra', '2º', 'ADM'),
('Emanuely de Souza Teixeira Barbosa', '2º', 'ADM'),
('Priscila Pinto Venceslau', '2º', 'ADM'),
('Camila Victória Peres', '2º', 'ADM'),
('Lucas Garbelini Piacente', '2º', 'ADM'),
('Maria Clara Delafiori Assolini', '2º', 'ADM'),
('Beatriz Lima Moreira', '1º', 'ADM'),
('Sofia Correia da Silva', '1º', 'ADM'),
('Carolina Gasparini Juliano', '2º', 'ADM'),
('Maria Antonia', '2º', 'ADM'),
('Livia Galindo', '2º', 'ADM'),
('Geovana Martins', '2º', 'ADM'),
('Maysa Vitória de Souza Cruz', '2º', 'ADM'),
('Laura Vitória Franco Ribeiro', '2º', 'ADM'),
('Sarah Cristina Meira', '2º', 'ADM'),
('Yudi Hatori Garcia', '2º', 'ADM'),
('Rebeca Amábile Gomes Carneiro Cruz', '2º', 'ADM'),
('Pedro Henrique Pereira da Silva', '2º', 'ADM'),
('Pedro', '2º', 'ADM'),
('Stella Maris', '1º', 'ADM'),
('Flávio Tavares de Moraes', '1º', 'DS'),
('Maria Eduarda Durães Cruz Mesquita', '1º', 'DS'),
('Miguel Roeda Silva', '1º', 'DS'),
('Dorival Camara Filho', '1º', 'DS'),
('Murilo Souza Targa', '1º', 'DS'),
('Felipe Gabriel Camargo Ribeiro Martins', '2º', 'DS'),
('David Peres Filho', '1º', 'DS'),
('Gustavo Alcântara Craiba', '1º', 'DS'),
('Davi Teixeira Galdino dos Santos', '1º', 'DS'),
('Beatriz Cristiny Teixeira Pires', '1º', 'DS'),
('Olivia Maria di Froscia Costa', '2º', 'DS'),
('Raquel Lissa Yamauti', '2º', 'DS'),
('Kauã Teixeira de Andrade', '1º', 'DS'),
('Maria Eduarda Rangel de Souza', '1º', 'DS'),
('Fernanda Alves Diniz', '2º', 'DS'),
('Hugo Nishikito Alexandre Soares', '2º', 'DS'),
('Davi Ferreira Neris', '1º', 'DS'),
('Enzo Bicalho Almeida', '1º', 'DS'),
('Kauã de Lira Guelfi', '1º', 'DS'),
('Heitor Pedroni Cruz', '1º', 'DS'),
('Ryan Augusto Resende de Oliveira', '1º', 'DS'),
('Eduardo da Silva Santos Silvestre de Menezes', '2º', 'DS'),
('André Romualdo da Silva Junior', '1º', 'DS'),
('Rafael Viana Pereira', '1º', 'DS'),
('Miguel Gabriel Luz de Melo', '1º', 'DS'),
('Miguel França', '1º', 'DS'),
('Marcelo Amancio Filho', '1º', 'DS'),
('Ana Clara Magalhães Souza', '1º', 'DS'),
('Eleno Doi Pillon', '1º', 'DS'),
('João Felipe Martins Marassi Cruz', '2º', 'DS'),
('Rafaela Bossoni', '2º', 'DS'),
('Beatriz Batista da Silva', '2º', 'DS'),
('Davi Diniz Dalevedo', '2º', 'DS'),
('Eduarda Leal Tavares', '2º', 'DS'),
('Nicolas Gabriel Venâncio dos Santos', '2º', 'DS'),
('Sibylla Daniel da Conceição', '2º', 'DS'),
('André Ricardo da Silva Nunes Gomes', '2º', 'DS'),
('Bruno Marques Pinheiro', '2º', 'DS'),
('Caio Fernando Faria', '2º', 'DS'),
('Guilherme Souza de Abreu', '2º', 'DS'),
('Gustavo Garbelini Piacente', '2º', 'DS'),
('Regina Doi Pillon', '1º', 'DS'),
('Bernardo Gabriel de Souza Gomes', '2º', 'DS'),
('Guilherme Antônio da Silva Vitória', '2º', 'DS'),
('Pedro Gabriel Nunes dos Santos', '2º', 'DS'),
('Samantha Maciel de Oliveira', '1º', 'DS'),
('Nathan Gabriel Affonso Cortello', '1º', 'DS'),
('Filipe Campos Bento Silva', '1º', 'DS'),
('Felipe Zorzatto Mazalli', '1º', 'DS'),
('Erick Henrique Piacente', '1º', 'DS'),
('Yuuki Losnaque Kameda', '2º', 'DS'),
('Antonio David de Souza Neto', '1º', 'DS'),
('Felipe dos Santos Leonardo', '2º', 'DS'),
('Daniel Bonfim de Oliveira', '2º', 'DS'),
('Guilherme Felicio Lopes', '2º', 'DS'),
('Henrique Carvalho Martins', '2º', 'DS'),
('Letícia Affonso Pingueiro', '2º', 'DS'),
('Sheyla Martinez Soares', '2º', 'DS'),
('Felipe Alves Canto', '1º', 'DS'),
('Gabriel Lucas Ferreira dos Santos', '1º', 'DS'),
('Heder de Souza Silva', '1º', 'DS'),
('Heitor Vinicius de Oliveira Bueno', '2º', 'DS'),
('Wesley Antunes Marreli', '1º', 'DS'),
('Vinicius Shoiti Ozawa', '2º', 'DS'),
('Gabriel Fernando de Souza', '2º', 'DS'),
('Isabella da Silva Ferreira', '2º', 'DS'),
('Leonardo Maximus Adão da Silva', '1º', 'DS'),
('Yasmin Barboza Candido', '1º', 'DS'),
('Lucas Henrique Rodrigues Caldas', '1º', 'DS'),
('Luis Otavio Sales Mendes', '1º', 'DS'),
('Gabriel Serra da Silva', '2º', 'DS'),
('Gabriel Ferreira Ferraz', '2º', 'DS');

-- 3. Inserção de inscrições (exemplo, continue para todos)
-- Supondo que IDs de alunos e oficinas são sequenciais conforme inserção
-- Exemplo: (aluno_id, oficina_id)
INSERT INTO public.inscricoes (aluno_id, oficina_id) VALUES
-- Exemplo: Amanda Castão Vaz em BACKEND: PYTHON (11H - 12H) seria (1,2)
-- Complete para todos os alunos/oficinas conforme a ordem de inserção
;

-- Observação: Para garantir integridade, confira os IDs após inserir alunos e oficinas, pois o serial pode variar.
-- Se quiser, posso gerar o bloco de inscrições já mapeando todos os alunos para todas as oficinas conforme os dados.
